### ISSUE TITLE
Invalid login token. Issuer doesn't match providerName

### ISSUE THREAD

**Issue by rvyasedh** [aws-samples/aws-cognito-dot-net-desktop-app#1]
I get this error when trying to access the  credentials.GetCredentials().AccessKey  Any help?

 CognitoAWSCredentials credentials =
   user.GetCognitoAWSCredentials(FED_POOL_ID, RegionEndpoint.USEast1);
 StringBuilder userlist = new StringBuilder();
 userlist.Append("================Cognito Credentails==================\n");
 userlist.Append("Access Key - " + credentials.GetCredentials().AccessKey);   <---------- errors here..

**Comment by koiker** [comment]
What is the error message?

**Comment by cosminenache** [comment]
Similarly to user rvyasedh, the application gets stuck when trying to access credentials object. The issue occurs in a web application. ASP.NET (4.6.1 framework).

The uploaded code works fine. Noticed a small issue there but not relevant for this problem (if the role associated to the identity pool does not have permissions to access S3, the application reports the username / password could not be validated, although it is an access issue, not an authentication issue).

When executed in a web application, in debug mode, the application seems to hang when it reaches the  credentials.GetCredentials().AccessKey instruction.
The application I have does exactly the same thing as this desktop application, only that it is a web application.
When I run in debug mode, I enter the username and password then F11 to step into the application. All works well until I get to the line bucketlist.Append("Access Key - " + credentials.GetCredentials().AccessKey);
When the execution reaches there, the control is given to the web application as if it waits an input from the web page (so I cannot proceed to the next line in the code).  

Any help, much appreciated.

**Comment by cosminenache** [comment]
Looks like the issue is the .NET framework I was using.
Supported version is 4.5

**Comment by koiker** [comment]
Thanks for the update!
