### ISSUE TITLE
User pool client XXX does not exist.

### ISSUE THREAD

**Issue by jerryszz** [aws-samples/aws-cognito-dot-net-desktop-app#5]
Hello,

I downloaded the code and tried to run locally. I've created my User Pool and added an user (Status: Confirmed). However, when the user signed in, an exception was thrown saying "User pool client XXX doesn't exist" in the following line the CognitorHelper class. 

await user.StartWithSrpAuthAsync(authRequest).ConfigureAwait(false);

I am new to AWS and have no clue what happened. I am sure I included the correct pool id and client id. 

Any ideas?

Thanks a lot.

**Comment by DominusDRR** [comment]
You must create an account in amazon cognito and write the IDs that are generated there. in your code 



https://stackoverflow.com/questions/64283854/user-management-in-aws-cognito-user-pool-using-c-sharp-and-net-core
